apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: kubevela-gitops
spec:
  components:
  - name: kubevela-gitops
    type: kustomize
    properties:
      repoType: git
      url: https://github.com/FogDong/bookinfo-authors
      secretRef: git-secret
      pullInterval: 1m
      git:
        branch: main
      path: ./release/app
      imageRepository:
        image: ghcr.io/fogdong/test-bookinfo-authors
        # secretRef: imagesecret
        filterTags:
          pattern: '^main-[a-f0-9]+-(?P<ts>[0-9]+)'
          extract: '$ts'
        policy:
          numerical:
            order: asc
        commitMessage: "Image: {{range .Updated.Images}}{{println .}}{{end}}"